### ISSUE TITLE
`vep_plugin_files` listed as optional parameter but pipeline won't run without it

### ISSUE THREAD

**Issue by fellen31** [nf-core/raredisease#593] opened 2024-08-13 11:22 UTC
### Description of the bug

`vep_plugin_files` listed as optional parameter but pipeline won't run without it

### Command used and terminal output

```console
ERROR ~ No such variable: ch_vep_extra_files

 -- Check script './workflows/raredisease.nf' at line: 516 or see '.nextflow.log' file for more details
```

**Comment by ramprasadn** [comment] 2024-08-14 13:07
Closing this issue since the issue is fixed in #594

**Closed by ramprasadn** 2024-08-14 13:07 UTC
Labels: bug
